services:
  server:
    build:
      context: .
      args:
        NODE_VERSION: 21.5.0
        PORT: 8080
    environment:
      NODE_ENV: production
      SOCKET: true
      PORT: 8080
      ALLOWED_SOCKET_ORIGINS: https://cdpn.io,http://localhost
      NODB: true
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/v1/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
